version: '3.1'

networks:
  kafka_network:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - kafka_network
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - kafka_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.103  # replaced with your Docker host IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    networks:
      - kafka_network
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: 192.168.0.103:9092  # corrected IP address
  microservice:
    image: my_app_gilhari
    container_name: microservice
    networks:
      - kafka_network
    ports:
      - "80:8081"
  microservice_2:
    image: my_app_gilhari_2
    container_name: microservice_2
    networks:
      - kafka_network
    ports:
      - "88:8088"